// To test getting root endpoint
GET http://localhost:3001/

###

// To test getting currencies
GET http://localhost:3001/api/currencies/

###

// To test getting particular currency by id
GET http://localhost:3001/api/currencies/2

###

// To test error handling for getting particular currency by id if it's not available in the data
GET http://localhost:3001/api/currencies/10


###

// To test adding currency (with hard coded information)
POST http://localhost:3001/api/currencies/
Content-Type: application/json

{
    "content": {
    "currencyCode": "CAD",
    "countryId": 7,
    "conversionRate": 0.75}
}

###

// To test error handling when info is missing on POST request (with hard coded information)
POST http://localhost:3001/api/currencies/
Content-Type: application/json

{
    "content": {
    "currencyCode": "",
    "country": "United Kingdom",
    "conversionRate": 0.59}
}

###

// To test modifying property conversionRate in a currency by id
PUT http://localhost:3001/api/currencies/2/0.74


###

// To test delete currency by id
DELETE http://localhost:3001/api/currencies/1

###

// To test unknown endpoint
GET http://localhost:3001/api/currenci

