name: deployment_pipeline

on:
  push:
    branches:
      - main

jobs:
  deployment_job:
    runs-on: ubuntu-latest
    steps:   
      - name: Checkout code
        uses: actions/checkout@v4
  
      - name: Setup Node environment
        uses: actions/setup-node@v4
  
      - name: Install server dependencies
        run: npm install
        working-directory: server
  
      - name: Run backend tests
        run: DB_URL=${{ secrets.DB_URL }} npm run test
        working-directory: server

      - name: Install client dependencies
        run: npm install
        working-directory: client

      - name: Run frontend tests
        run: npm run test
        working-directory: client


      
